glug/blogs/urls.py
from django.urls import path
from blogs import views

app_name = 'blogs'

urlpatterns = [
	path('',views.index,name='index'),
]

glug/glug/urls.py
from django.contrib import admin
from django.urls import path,include
from glug import views

urlpatterns = [
    #path('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
    path('users/',include('users.urls')),
    path('events/',include('events.urls')),
    
]

glug/urls.py
from django.contrib import admin
from django.urls import path,include
#from glug import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #path('',views.index,name="index"),
    path('',include('users.urls')),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
    
    path('events/',include('events.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

glug/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
	path('',views.index,name='index'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name="logout"),
	path('register/',views.register,name='register'),
	path('data_feed/',views.data_feed,name='data_feed'),
	path('event_create/',views.event_create,name='event_create'),
	
]

users/urls.py
from django.urls import path
from users import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
	path('',views.home,name='home'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name="logout"),
	path('register/',views.register,name='register'),
	path('event_create/',views.event_create,name='event_create'),
	path('cancel/',views.cancel,name='cancel'),
	path('event_apply/',views.event_apply,name='event_apply'),
	path('dashboard_edit/', views.dashboard_edit, name="dashboard_edit"),
	path('dashboard/', views.dashboard, name="dashboard"),
	path('info/',views.info, name="info"),
	path('resetpassword/',views.resetpassword,name="resetpassword"),
	path('verifyemail/',views.verifyemail,name="verifyemail"),
	
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

glug/blogs/models.py
from django.db import models

# Create your models here.

glug/events/models.py
from django.db import models

# Create your models here.
class Scan(models.Model):
    im =  models.ImageField(upload_to='images/')
 

glug/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Userdetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    usn = models.CharField(max_length=50)
    

users/models.py
from django import db
db.connections.close_all()

glug/events/forms.py
from django import forms
from events.models import *


class photo_form(forms.ModelForm):
    class Meta:
        model = Scan
        fields = ['im']

glug/blogs/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blogs/index.html')

glug/events/views.py
from django.shortcuts import render
import argparse
import io
import re
import os
from events.forms import *


# Create your views here.
def index(request):
    return render(request, 'events/index.html')

def Scan(request):
    
    if request.method == 'POST':
        im_form = photo_form(request.POST, request.FILES)
        if im_form.is_valid():
            im_form.save()
            #extracting the file name of the image being uploaded
            for filename, file in request.FILES.items():
                f_name = request.FILES[filename].name

            BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            path =  os.path.join(BASE_DIR, 'media/images/'+f_name)
            #path = os.path.join(path,f_name)
            
            
                
            """Detects text in the file."""
            from google.cloud import vision
            client = vision.ImageAnnotatorClient()

            # [START vision_python_migration_text_detection]
            with io.open(path, 'rb') as image_file:
                content = image_file.read()

            image = vision.types.Image(content=content)

            response = client.text_detection(image=image)
            texts = response.text_annotations
            print('Texts:')
            s = []
            for text in texts:
                s.append(text.description)

            return render(request,'events/verify.html',{'im_form':s})
                
    
    else:
        im_form = photo_form()
    return render(request,'events/result.html',{'im_form':im_form})

glug/glug/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'index.html')

glug/users/views.py
from django.shortcuts import render
import pyrebase 
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from google.oauth2 import id_token
from google.auth.transport import requests



config = {
    'apiKey': "AIzaSyBd9iPWogpUFx0uDNGTL1LwiYgWIYIFMJI",
    'authDomain': "glug-mvit1.firebaseapp.com",
    'databaseURL': "https://glug-mvit1.firebaseio.com",
    'projectId': "glug-mvit1",
    'storageBucket': "glug-mvit1.appspot.com",
    'messagingSenderId': "58837097878",
    'serviceAccount':"/Users/aditya/Desktop/glug_website/glug_website_django/glug/glug-mvit1-firebase-adminsdk-e5ljh-474945bd09.json"

}
firebase = pyrebase.initialize_app(config)
authe = firebase.auth()
db=firebase.database()
cred = credentials.ApplicationDefault()
firebase_admin.initialize_app(cred, {
  'projectId': "glug-mvit1",
})


# Create your views here
# .
def index(request):
    user = ""
    event_data = db.child("Created Events").get()
    dis_data = []
    event_detail = []
    for data in event_data.each():
        dis_data.append(data.val())
    print(dis_data)
    text = {}
    for i in dis_data:
        text = i
        for v in text.values():
            for x in v.values():
                event_detail.append(x)
    print(event_detail)
    if request.method == "POST":
        value = request.POST.get('sub_mit')
        try:
            user = request.session['user']
            print(user)
            print("index")
            print(user['email'],user['registered'])
            user = user
            
            idtoken = request.session['uid']
            a = authe.get_account_info(idtoken)
            if value == 'Register Your Event':
                value = 3
            if value == 'Register your Project':
                value = 4
            print("If try")
            user_f = {'registered':True}
            return render(request, 'index.html',{'value':value,'user':user,'user_f':user_f['registered'],'event_detail':event_detail})
            
        except:
            if value == "Register Now":
                value = 1
            if value == "Login":
                value = 2
            user_f = {'registered':False}
            print("If Except")
            return render(request, 'index.html',{'value':value,'user':user,'user_f':user_f['registered'],'event_detail':event_detail})
    else:
        try:
            user = request.session['user']
            value = 3
            user = user
            print("Else try")
            print(user['registered'])
            user_f = {'registered':True}
            return render(request,'index.html',{'value':value,'user':user ,'user_f':user_f['registered'],'event_detail':event_detail})
        except:
            print("Else Except")
            value = 2
            user_f = {'registered':False}
            print(user_f['registered'])
            return render(request,'index.html',{'value':value,'user_f':user_f['registered'],'event_detail':event_detail})
        

def login(request):
    if request.method == "POST":
        email=request.POST.get('email')
        password = request.POST.get("password")
        try:
            user = authe.sign_in_with_email_and_password(email,password)
            authe.get_account_info(user['idToken'])
            session_id=user['idToken']
            request.session['uid']=str(session_id)
            request.session['user'] = user
            print(user)
            print(user['email'])
            print("login")
            authe.refresh(user['refreshToken'])
            return HttpResponseRedirect("/users")
        except:
            message="invalid credentials"
            print(message)
            return HttpResponseRedirect("/users",{'msg':message})
    else:
        return HttpResponseRedirect("/users")
#register view
def register(request):
    if request.method == "POST":
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        confirm_password=request.POST.get('password')
        if password == confirm_password:
            try:
                user=authe.create_user_with_email_and_password(email,password)
                new_user = authe.send_email_verification(user['idToken'])
                print(new_user)
                print(user)
                uid = user['localId']
                
                data={"displayName":username,"verified":"0",'email':email,'password':password}
                db.child("users").child(uid).child("details").set(data)
                print("Registered")
                user_login = authe.sign_in_with_email_and_password(email,password)
                authe.get_account_info(user_login['idToken'])
                session_id=user['idToken']
                request.session['uid']=str(session_id)
                request.session['user'] = user_login
                return HttpResponseRedirect("/users")
            except:
                print("Error")
                message="Unable to create account try again"
                return render(request,"index.html",{"messg":message})
        else:
            message = "Password Didn't Match"
            return render(request,"index.html",{"messg":message})
    else:
        return render(request,"index.html")



def data_feed(request):
    if request.method == "POST":
        name = request.POST.get('name')
        verified = request.POST.get('verified')
        last_name = request.POST.get('l_name')
        data={'name':name,'verified':verified,'last_name':last_name}
        idtoken = request.session['uid']
        a = authe.get_account_info(idtoken)
        a = a['users'][0]
        a= a['localId']
        db.child('profile').child(a).child('details').update(data)
        
    else:
        return render(request, 'users/feed.html')
#creating event        
def event_create(request):
    if request.method == "POST":
        user = request.session['user']
        tag = request.POST.get('tag')
        event_name = request.POST.get('event_name')
        event_date=request.POST.get('event_date')
        event_price = request.POST.get('event_price')
        event_time=request.POST.get('event_time')
        event_venue = request.POST.get('event_venue')
        event_details = request.POST.get('event_details')
        idtoken = request.session['uid']
        a = authe.get_account_info(idtoken)
        a = a['users'][0]
        a= a['localId']
        data = {
            'tag':tag,
            'event_name':event_name,
            'created_by':user['email'],
            'created_id':a,
            'event_date':event_date,
            'event_time':event_time,
            'event_venue':event_venue,
            'event_details':event_details,
            'event_price':event_price
        }
        db.child('Created Events').child(tag).child(event_name).child('details').update(data)
        return HttpResponseRedirect('/users')

    else:
        return render(request, 'users/event_create.html')


#logout view
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/users/')

glug/templates/users/event_create.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>My fake blog!</title>

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
</head>
<body>
<form action="{% url 'users:event_create' %}" method="post">
{% csrf_token %}
feed :
<p>
    <label for="tag">tag</label>
    <select id = "myList" name="tag">
    <option value = "ml" name="tag">Machine Learning</option>
    <option value = "cs" name="tag">Cyber Security</option>
    <option value = "wd" name="tag">Web Development</option>
    <option value = "ad" name="tag">App Development</option>
    </select>
</p>
<input type="text" name="event_name" value="event_name"><br><br>
<input type="text" name="event_date" value="event_date"><br><br>
<input type="text" name="event_price" value="event_price"><br><br>
<input type="text" name="event_time" value="event_time"><br><br>
<input type="text" name="event_venue" value="event_venue"><br><br>
<input type="text" name="event_details" value="event_details"><br><br>

<input type="submit" value="login">
    
</form>
</body>
</html>

glug/templates/users/feed.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>My fake blog!</title>

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
</head>
<body>
<form action="{% url 'users:data_feed' %}" method="post">
{% csrf_token %}
feed :
<input type="text" name="name"><br><br>
<input type="number" name="verified"><br><br>
<input type="text" name="l_name"><br><br>

<input type="submit" value="login">
    
</form>
</body>
</html>

glug/templates/users/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>My fake blog!</title>

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
</head>
<body>
  {% csrf_token %}
  Welcome {{email}}
</body>
</html>

glug/templates/users/signin.html
{% if messg %}
<script>
    alert('{{ messg }}');
</script>
{% endif %}
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sign</title>
</head>
<body>
<form action="{% url 'users:login' %}" method="post">
{% csrf_token %}
Email :
<input type="email" name="email"><br><br>
Password:
<input type="password" name="pass"><br><br>
<input type="submit" value="login">
    <button type="button" onclick="location.href='{% url "users:signUp" %}'">SignUp</button>
</form>
</body>
</html>

glug/templates/users/signup.html
{% if messg %}
<script>
    alert('{{ messg }}');
</script>
{% endif %}
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sign</title>
</head>
<body>
<form action="{% url 'users:postsignup' %}" method="post">
    {% csrf_token %}
    Name:
    <input type="text" name="name"><br><br>
    Email :
    <input type="email" name="email"><br><br>
    Password:
    <input type="password" name="pass"><br><br>
    <input type="submit" value="SignUp">
</form>
</body>
</html>