glug/glug/urls.py
from django.contrib import admin
from django.urls import path,include
from glug import views

urlpatterns = [
    #path('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
    path('users/',include('users.urls')),
    path('events/',include('events.urls')),
    
]

glug/urls.py
from django.contrib import admin
from django.urls import path,include
#from glug import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #path('',views.index,name="index"),
    path('',include('users.urls')),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
    
    path('events/',include('events.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

glug/users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
	path('',views.index,name='index'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name="logout"),
	path('register/',views.register,name='register'),
	path('data_feed/',views.data_feed,name='data_feed'),
	path('event_create/',views.event_create,name='event_create'),
	
]

users/urls.py
from django.urls import path
from users import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
	path('',views.home,name='home'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name="logout"),
	path('register/',views.register,name='register'),
	path('event_create/',views.event_create,name='event_create'),
	path('cancel/',views.cancel,name='cancel'),
	path('event_apply/',views.event_apply,name='event_apply'),
	path('dashboard_edit/', views.dashboard_edit, name="dashboard_edit"),
	path('dashboard/', views.dashboard, name="dashboard"),
	path('info/',views.info, name="info"),
	path('resetpassword/',views.resetpassword,name="resetpassword"),
	path('verifyemail/',views.verifyemail,name="verifyemail"),
	
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

glug/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Userdetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    usn = models.CharField(max_length=50)
    

users/models.py
from django import db
db.connections.close_all()

glug/users/views.py
from django.shortcuts import render
import pyrebase 
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from google.oauth2 import id_token
from google.auth.transport import requests



config = {
    'apiKey': "AIzaSyBd9iPWogpUFx0uDNGTL1LwiYgWIYIFMJI",
    'authDomain': "glug-mvit1.firebaseapp.com",
    'databaseURL': "https://glug-mvit1.firebaseio.com",
    'projectId': "glug-mvit1",
    'storageBucket': "glug-mvit1.appspot.com",
    'messagingSenderId': "58837097878",
    'serviceAccount':"/Users/aditya/Desktop/glug_website/glug_website_django/glug/glug-mvit1-firebase-adminsdk-e5ljh-474945bd09.json"

}
firebase = pyrebase.initialize_app(config)
authe = firebase.auth()
db=firebase.database()
cred = credentials.ApplicationDefault()
firebase_admin.initialize_app(cred, {
  'projectId': "glug-mvit1",
})


# Create your views here
# .
def index(request):
    user = ""
    event_data = db.child("Created Events").get()
    dis_data = []
    event_detail = []
    for data in event_data.each():
        dis_data.append(data.val())
    print(dis_data)
    text = {}
    for i in dis_data:
        text = i
        for v in text.values():
            for x in v.values():
                event_detail.append(x)
    print(event_detail)
    if request.method == "POST":
        value = request.POST.get('sub_mit')
        try:
            user = request.session['user']
            print(user)
            print("index")
            print(user['email'],user['registered'])
            user = user
            
            idtoken = request.session['uid']
            a = authe.get_account_info(idtoken)
            if value == 'Register Your Event':
                value = 3
            if value == 'Register your Project':
                value = 4
            print("If try")
            user_f = {'registered':True}
            return render(request, 'index.html',{'value':value,'user':user,'user_f':user_f['registered'],'event_detail':event_detail})
            
        except:
            if value == "Register Now":
                value = 1
            if value == "Login":
                value = 2
            user_f = {'registered':False}
            print("If Except")
            return render(request, 'index.html',{'value':value,'user':user,'user_f':user_f['registered'],'event_detail':event_detail})
    else:
        try:
            user = request.session['user']
            value = 3
            user = user
            print("Else try")
            print(user['registered'])
            user_f = {'registered':True}
            return render(request,'index.html',{'value':value,'user':user ,'user_f':user_f['registered'],'event_detail':event_detail})
        except:
            print("Else Except")
            value = 2
            user_f = {'registered':False}
            print(user_f['registered'])
            return render(request,'index.html',{'value':value,'user_f':user_f['registered'],'event_detail':event_detail})
        

def login(request):
    if request.method == "POST":
        email=request.POST.get('email')
        password = request.POST.get("password")
        try:
            user = authe.sign_in_with_email_and_password(email,password)
            authe.get_account_info(user['idToken'])
            session_id=user['idToken']
            request.session['uid']=str(session_id)
            request.session['user'] = user
            print(user)
            print(user['email'])
            print("login")
            authe.refresh(user['refreshToken'])
            return HttpResponseRedirect("/users")
        except:
            message="invalid credentials"
            print(message)
            return HttpResponseRedirect("/users",{'msg':message})
    else:
        return HttpResponseRedirect("/users")
#register view
def register(request):
    if request.method == "POST":
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        confirm_password=request.POST.get('password')
        if password == confirm_password:
            try:
                user=authe.create_user_with_email_and_password(email,password)
                new_user = authe.send_email_verification(user['idToken'])
                print(new_user)
                print(user)
                uid = user['localId']
                
                data={"displayName":username,"verified":"0",'email':email,'password':password}
                db.child("users").child(uid).child("details").set(data)
                print("Registered")
                user_login = authe.sign_in_with_email_and_password(email,password)
                authe.get_account_info(user_login['idToken'])
                session_id=user['idToken']
                request.session['uid']=str(session_id)
                request.session['user'] = user_login
                return HttpResponseRedirect("/users")
            except:
                print("Error")
                message="Unable to create account try again"
                return render(request,"index.html",{"messg":message})
        else:
            message = "Password Didn't Match"
            return render(request,"index.html",{"messg":message})
    else:
        return render(request,"index.html")



def data_feed(request):
    if request.method == "POST":
        name = request.POST.get('name')
        verified = request.POST.get('verified')
        last_name = request.POST.get('l_name')
        data={'name':name,'verified':verified,'last_name':last_name}
        idtoken = request.session['uid']
        a = authe.get_account_info(idtoken)
        a = a['users'][0]
        a= a['localId']
        db.child('profile').child(a).child('details').update(data)
        
    else:
        return render(request, 'users/feed.html')
#creating event        
def event_create(request):
    if request.method == "POST":
        user = request.session['user']
        tag = request.POST.get('tag')
        event_name = request.POST.get('event_name')
        event_date=request.POST.get('event_date')
        event_price = request.POST.get('event_price')
        event_time=request.POST.get('event_time')
        event_venue = request.POST.get('event_venue')
        event_details = request.POST.get('event_details')
        idtoken = request.session['uid']
        a = authe.get_account_info(idtoken)
        a = a['users'][0]
        a= a['localId']
        data = {
            'tag':tag,
            'event_name':event_name,
            'created_by':user['email'],
            'created_id':a,
            'event_date':event_date,
            'event_time':event_time,
            'event_venue':event_venue,
            'event_details':event_details,
            'event_price':event_price
        }
        db.child('Created Events').child(tag).child(event_name).child('details').update(data)
        return HttpResponseRedirect('/users')

    else:
        return render(request, 'users/event_create.html')


#logout view
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/users/')

templates/users/dashboard.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class="intro-section single-cover" id="home-section">
      
      <div class="slide-1 " style="background-image: url('/static/images/img_2.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12"><br><br>
              <div class="row justify-content-center align-items-center text-center">
                <div class="col-lg-6">
                  <h1 data-aos="fade-up" data-aos-delay="0">Hi, {{ user.first_name }}</h1>
                  <p data-aos="fade-up" data-aos-delay="100">We are a community of  <a href="" class="text-white">{{ total_user_count }} members </a> and counting</p>
                </div>
                
                
              </div>
              <div class=" text-center">
              
               <a href="{% url 'users:resetpassword' %}"><input type="submit" data-aos="fade-up" data-aos-delay="100" class=" btn btn-outline-info text-center" style="align:right;" name="ev_submit" value="Reset Password" /></a>
               <a href="{% url 'users:dashboard_edit' %}"><input type="submit" data-aos="fade-up" data-aos-delay="100" class=" btn btn-outline-info text-center" style="align:right;" name="ev_submit" value=" Edit Your Profile " /></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<div class="site-section bg-light" id="event_create_section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7">
                <h2 class="section-title mb-3">Profile Details</h2><br><br>
                <div class="col-md-8 text-center testimony">
                {% if user.dp_url %}
                  <img src="{{ user.dp_url }}" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
                {% else %}
                <img src="/static/images/user_avatar.jpeg" alt="Image" class="img-fluid w-25 mb-4 rounded-circle">
                {% endif %}
                </div>
               
                <h4>Name : {{ user.first_name }}&nbsp;&nbsp;{{ user.last_name }} </h4>
                <h4>Date of Birth : {{ user.dob }}</h4>
                <h4>USN : {{ user.usn }}</h4>
                <h4>Sem : {{ user.sem }}</h4>
                <h3>I am ,<h3>
                <h4>{{ user.desc }}</h4>
                <h4 class="mb-5">Email : {{ user.email }}&nbsp;&nbsp;
                {% if user.emailVerified %}<span class="icon-check-circle" style="color:green;"></span>
                {% else %}<span class="icon-times-circle" style="color:red;"></span>
                {% endif %} &nbsp;&nbsp;{% if not user.emailVerified %}
                <p style="color:red;">Check your email to verify your account</p>
                <p>If Already Verified&nbsp;&nbsp;<a href="{% url 'users:verifyemail' %}">Click Here</a></p>
                {% endif %}</h4>
                <h4>Contact Number : {{ user.contact_number }}</h4>
                <!--<form method="post" action="{% url 'users:dashboard' %}" data-aos="fade" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="text" name="event_name" class="form-control" placeholder="Name of the Event" required>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-6 mb-3 mb-lg-0">
                      Upload your picture : 
                    </div>
                    <div class="col-md-6">
                      <input type="file" name="img_event" class="form-control" placeholder="">
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <div class="col-md-4 mb-3 mb-lg-0">
                      <input type="text" name="event_date" class="form-control datepicker" placeholder="Click to Select a date" >
                    </div>
                    <div class="col-md-4">
                      <input type="text" name="event_time" class="form-control" placeholder="Time of the Event" >
                    </div>
                    <div class="col-md-4">
                      <input type="text" name="event_venue" class="form-control" placeholder="Venue" >
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="text" name="event_price" class="form-control" placeholder="Registration Fee" required>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="text" name="event_headline" class="form-control" placeholder="Brief headline to be displayed... in 100 words" maxlength="100" required>
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <div class="col-md-12">
                      <textarea class="form-control" name="event_details" cols="30" rows="10" placeholder="Write Details ot the Event..."></textarea>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="text" name="tag" class="form-control" placeholder="Tags : Separate all tags by comma">
                      <p>Tag : App,Web,ML,AI,Data Science,Anything New</p>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="email" class="form-control" placeholder="{{ user.email }}" disabled/>
                    </div>
                  </div>
                  
                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="number" name="contact_number" class="form-control" placeholder="Enter the Contact number" required>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="submit" class="btn btn-outline-primary py-3 px-6 ml-auto " value="Create Event">&nbsp;&nbsp;&nbsp;
                      <a href="{% url 'users:cancel' %}"><input target="" type="button" class="btn btn-outline-danger py-3 px-6 nl-auto" value="Cancel"></a>
                    </div>
                  </div>
                </form>
                -->
                {{ users_profile.email }}
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

templates/users/dashboard_edit.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class="intro-section single-cover" id="home-section">
      <div class="slide-1 " style="background-image: url('/static/images/img_2.jpg');" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row justify-content-center align-items-center text-center">
                <div class="col-lg-6"><br>
                  <h1 data-aos="fade-up" data-aos-delay="0">It's always nice to be updated</h1>
                  <p data-aos="fade-up" data-aos-delay="100"> </p>
                </div>
              </div>
              <div class=" text-center">
              <a href="{% url 'users:dashboard' %}"><input type="submit" class=" btn btn-outline-info text-center" style="align:right;" name="ev_submit" value=" Dashboard " /></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

<div class="site-section bg-light" id="event_create_section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7">
                <h2 class="section-title mb-3 text-center">Edit your Dashboard</h2>
                <p class="mb-5"></p>
                <form method="post" action="{% url 'users:dashboard_edit' %}" data-aos="fade" enctype="multipart/form-data">
                {% csrf_token %}
                  <div class="form-group row">
                    <div class="col-md-6 mb-3 mb-lg-0">
                      <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}" />
                    </div>
                    <div class="col-md-6">
                      <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}">
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-6 mb-3 mb-lg-0">
                      Upload Your Profile Picture : 
                    </div>
                      <div class="col-md-6">
                      <input type="file" name="dp" class="form-control" placeholder="">
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-4 mb-3 mb-lg-0">
                      <input type="text" name="dob" class="form-control datepicker" {% if user.dob %} value="{{ user.dob }}"{% else %} placeholder="Date of Birth"{% endif %} >
                    </div>
                    <div class="col-md-4">
                      <input type="text" name="usn" class="form-control" {% if user.usn %} value="{{ user.usn }}"{% else %} placeholder="Enter your USN" {% endif %}>
                    </div>
                    <div class="col-md-4">
                      <input type="text" name="sem" class="form-control" {% if user.sem %} value="{{ user.sem }}"{% else %}  placeholder="Enter your Sem" {% endif %}>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-12">
                      <textarea class="form-control" name="desc" cols="30" rows="10" placeholder="Describe Yourself" {% if user.sem %} value="{{ user.desc }}" {% endif %}></textarea>
                    </div>
                  </div>
                  <!--
                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="text" name="tag" class="form-control" placeholder="Tags : Separate all tags by comma">
                      <p>Tag : App,Web,ML,AI,Data Science,Anything New</p>
                    </div>
                  </div>-->

                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="text" name="email" class="form-control" value="{{ user.email }}" disabled/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="number" name="contact_number" class="form-control" value="{{ user.contact_number }}" disabled/>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-md-12">
                      <input type="submit" class="btn btn-outline-primary py-3 px-6 ml-auto " value="Submit">&nbsp;&nbsp;&nbsp;
                      <a href="{% url 'users:cancel' %}"><input target="" type="button" class="btn btn-outline-danger py-3 px-6 nl-auto" value="Cancel"></a>
                    </div>
                  </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>



{% endblock %}