glug/events/urls.py
from django.urls import path
from events import views

app_name = 'events'

urlpatterns = [
	path('',views.index,name='index'),
	path('scan/',views.Scan,name='scan'),
]

glug/glug/urls.py
from django.contrib import admin
from django.urls import path,include
from glug import views

urlpatterns = [
    #path('',views.home,name="home"),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
    path('users/',include('users.urls')),
    path('events/',include('events.urls')),
    
]

glug/urls.py
from django.contrib import admin
from django.urls import path,include
#from glug import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #path('',views.index,name="index"),
    path('',include('users.urls')),
    path('admin/', admin.site.urls),
    path('blogs/',include('blogs.urls')),
    
    path('events/',include('events.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
	path('',views.home,name='home'),
	path('login/',views.login,name='login'),
	path('logout/',views.logout,name="logout"),
	path('register/',views.register,name='register'),
	path('event_create/',views.event_create,name='event_create'),
	path('cancel/',views.cancel,name='cancel'),
	path('event_apply/',views.event_apply,name='event_apply'),
	path('dashboard_edit/', views.dashboard_edit, name="dashboard_edit"),
	path('dashboard/', views.dashboard, name="dashboard"),
	path('info/',views.info, name="info"),
	path('resetpassword/',views.resetpassword,name="resetpassword"),
	path('verifyemail/',views.verifyemail,name="verifyemail"),
	
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

events/models.py
from django import db
db.connections.close_all()

glug/events/models.py
from django.db import models

# Create your models here.
class Scan(models.Model):
    im =  models.ImageField(upload_to='images/')
 

glug/events/forms.py
from django import forms
from events.models import *


class photo_form(forms.ModelForm):
    class Meta:
        model = Scan
        fields = ['im']

glug/events/views.py
from django.shortcuts import render
import argparse
import io
import re
import os
from events.forms import *


# Create your views here.
def index(request):
    return render(request, 'events/index.html')

def Scan(request):
    
    if request.method == 'POST':
        im_form = photo_form(request.POST, request.FILES)
        if im_form.is_valid():
            im_form.save()
            #extracting the file name of the image being uploaded
            for filename, file in request.FILES.items():
                f_name = request.FILES[filename].name

            BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            path =  os.path.join(BASE_DIR, 'media/images/'+f_name)
            #path = os.path.join(path,f_name)
            
            
                
            """Detects text in the file."""
            from google.cloud import vision
            client = vision.ImageAnnotatorClient()

            # [START vision_python_migration_text_detection]
            with io.open(path, 'rb') as image_file:
                content = image_file.read()

            image = vision.types.Image(content=content)

            response = client.text_detection(image=image)
            texts = response.text_annotations
            print('Texts:')
            s = []
            for text in texts:
                s.append(text.description)

            return render(request,'events/verify.html',{'im_form':s})
                
    
    else:
        im_form = photo_form()
    return render(request,'events/result.html',{'im_form':im_form})

templates/events/info.html
{% extends "index.html" %}
{% load static %}
{% block content %}

<div class="intro-section single-cover" id="home-section">
      {% if img_event_url %}
      <div class="slide-1 " style="background-image: url('{{ img_event_url }}');" data-stellar-background-ratio="0.5">
      {% else %}
      <div class="slide-1 " style="background-image: url('/static/images/img_2.jpg');" data-stellar-background-ratio="0.5">
      {% endif %}<br>
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12">
              <div class="row justify-content-center align-items-center text-center">
                <div class="col-lg-6">
                  <h1 data-aos="fade-up" data-aos-delay="0" style="text-transform:uppercase;">{{ event_name }}</h1>
                  <p data-aos="fade-up" data-aos-delay="0">{{ event_headline}}</p>
                  <!--<p data-aos="fade-up" data-aos-delay="100">{{ event_detail_count }} Lessons / 12 Week &bullet; 2,193 students &bullet; <a href="#" class="text-white">6 comments</a></p>-->
                </div>

                
              </div>
              <div class=" text-center">
              
              <form action="{% url 'users:event_apply' %}" method="post" class="">
                  {% csrf_token %}
                  <input type="number" name="year" value="{{ year }}" hidden>
                  <input type="number" name="month" value="{{ month }}" hidden>
                  <input type="number" name="date" value="{{ date }}" hidden>
                  <input type="text" name="event_name" value="{{ event_name }}" hidden>
                  
                  
                    <!--<div class="py-3 px-4"><span class="btn btn-outline-info">More Info</span></div></a>-->
                    <div class="py-3 px-4">
                        {% if curr_time.curr_year <= year and curr_time.curr_month <= month and curr_time.curr_date <= date %}
                        
                      
                        {% if found == 1  %}
                        
                        <input type="button" data-aos="fade-up" data-aos-delay="10" class=" btn btn-danger" style="align:right;" name="submit" value="Applied" disabled/>
                        
                        {% else %}
                        {% if user.email %}
                        <input type="submit" data-aos="fade-up" data-aos-delay="10" onclick="myFunction()" class=" btn btn-outline-danger" style="align:right;" name="submit" value="Apply" />



                        {% else %}
                        <a href="{% url 'users:login' %}"><input type="button" class=" btn btn-outline-danger" style="align:right;" name="submit" value="Login to Apply"/></a>
                        {% endif %}
                        {% endif %}
                        {% else %}
                        <input type="button" data-aos="fade-up" data-aos-delay="10" class=" btn btn-danger" style="align:right;" name="submit" value="Event Expired" disabled/>
                        {% endif %}
                        
                    </div>
                </form>
              
              
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>

<div class="site-section bg-light" id="event_create_section">
<div class="teacher text-center">
<p>
  <span class="icon-map-marker">&nbsp;{{ event_venue }}{{ created_by_name }}</span> &nbsp; 
</p>
<p>
  <span class="icon-date_range text-center"></span>{{ month_str }}&nbsp;{{ date }},&nbsp; {{ year }} <span class="icon-timer"></span>{{ event_time }}  
</p>
<p>{% if event_price == 0 %}
<input data-aos="" data-aos-delay="" class="btn  btn-black py-3 px-5" type="submit"  value="F R E E "/>
{% else %}
<input data-aos="" data-aos-delay="" class="btn btn-dark py-3 px-5" type="submit"  value="Rs &nbsp;&nbsp;{{ event_price }}"/>
{% endif %}
</p>
</div> 


          <div class="container">
            
            <div class="row justify-content-center">
              <div class="col-md-7">
                {% for det in event_details %}
                
                <h2>{{ det }}.
                </h2><br>
                {% endfor %}
                <br><br><br><br>
                <p>Contact : </p>
                <p>{{ created_by_name }}</p>
                <p><a href="callto:{{ contact_number }}"<span class="icon-phone2"></span>&nbsp;{{ contact_number }}</a>&nbsp;</p>
                <p><a href="mailto:{{ created_by_email }}?Subject=Regarding%20the%20Event%20{{item.event_name}}&body=Hi,%20I%20am%20{{ user.email }}%0AI%20get%20to%20know%20about%20{{ item.event_name }}%20on%20GLUG%20Website%0A%0A%0A%0A"<span class="icon-envelope-o"></span>&nbsp;{{ created_by_email }}</a></p>
                
                
                <p>Alternate Contact : </p>
                {% if alt_name %}
                
                <p>{{ alt_name }}</p>
                {% endif %}
                {% if alt_contact %}
                <p><a href="callto:{{ alt_contact }}"<span class="icon-phone2"></span>&nbsp;{{ alt_contact }}</a>&nbsp;</p>
                {% endif %}
                {% if alt_email %}
                <p><a href="mailto:{{ alt_email }}?Subject=Regarding%20the%20Event%20{{item.event_name}}&body=Hi,%20I%20am%20{{ user.email }}%0AI%20get%20to%20know%20about%20{{ item.event_name }}%20on%20GLUG%20Website%0A%0A%0A%0A"<span class="icon-envelope-o"></span>&nbsp;{{ alt_email }}</a></p>
                {% endif %}
                <h2 class="section-title mb-3"></h2>
               

                
                </div>
              </div>
            </div>
          </div>
          
        </div>


<script>
function myFunction() {
  alert("APPLIED SUCCESSFULLY");
}
</script>

{% endblock %}